import "server-only";
import { createHash } from "node:crypto";
import { getIntentProvider } from "./ai/openai";
import { formatBusinessDate, getBusinessDate, monthRange, resolveDateReference } from "./dates";
import { createTelegramDraft, findExistingEntries, getActiveEmployeeEntities, getActiveProjectEntities, getConversationContext, queryReport, saveConversationContext, type ResolvedDraftEntry } from "./data";
import { resolveEntity, type NamedEntity } from "./resolution";

export type NaturalReply={text:string;inlineKeyboard?:Array<Array<{text:string;callback_data:string}>>};
const entityError=(kind:"employee"|"project",ref:string,res:ReturnType<typeof resolveEntity>)=>res.kind==="ambiguous"?`לאיזה ${kind==="employee"?"עובד":"פרויקט"} התכוונת?\n${res.options.map(x=>`• ${x.name}`).join("\n")}`:kind==="employee"?`לא נמצא עובד בשם "${ref}". יש לתקן את השם או להוסיף אותו דרך מערכת ה-Web.`:`לא נמצא פרויקט התואם ל-"${ref}".`;

function formatDraft(entries:ResolvedDraftEntry[],duplicates:boolean){const groups=new Map<string,ResolvedDraftEntry[]>();entries.forEach(e=>{const key=`${e.work_date}|${e.project_name}`;groups.set(key,[...(groups.get(key)||[]),e]);});const body=[...groups].map(([key,rows])=>{const [date,project]=key.split("|");return `📅 ${formatBusinessDate(date)}\n📍 ${project}\n\n${rows.map(e=>`• ${e.employee_name} — ${e.regular_hours+e.overtime_hours} שעות`).join("\n")}`;}).join("\n\n");const total=entries.reduce((a,e)=>a+e.regular_hours+e.overtime_hours,0);const duplicateText=duplicates?`\n\n⚠️ כבר קיים דיווח:\n${entries.filter(e=>e.existing_hours!==null).map(e=>`${e.employee_name} — ${e.project_name} — ${formatBusinessDate(e.work_date)}\nקיים: ${e.existing_hours} שעות\nחדש: ${e.regular_hours+e.overtime_hours} שעות`).join("\n\n")}\n\nהאישור יעדכן את הדיווחים הקיימים.`:"";return `📝 טיוטת דיווח\n\n${body}\n\nסה״כ: ${total} שעות${duplicateText}\n\nהאם לשמור את הדיווח?`;}
function reportRange(report:{date_reference:string|null;date_from_reference:string|null;date_to_reference:string|null},businessDate:string,previous:Record<string,unknown>|null){if(report.date_from_reference&&report.date_to_reference){const from=resolveDateReference(report.date_from_reference,businessDate),to=resolveDateReference(report.date_to_reference,businessDate);return from&&to?{from,to}:null;}if(report.date_reference){if(report.date_reference.includes("חודש")||/[א-ת]+בר|מרץ|מאי|יוני|יולי|אוגוסט|אפריל/.test(report.date_reference)){const monthly=monthRange(report.date_reference,businessDate);if(monthly)return{from:monthly[0],to:monthly[1]};}const single=resolveDateReference(report.date_reference,businessDate);return single?{from:single,to:single}:null;}if(previous?.from&&previous?.to)return{from:String(previous.from),to:String(previous.to)};const current=monthRange("החודש",businessDate)!;return{from:current[0],to:current[1]};}

export async function handleNaturalMessage(chatId:number,userId:number,message:string):Promise<NaturalReply>{const businessDate=getBusinessDate();const [projects,employees,previous]=await Promise.all([getActiveProjectEntities(),getActiveEmployeeEntities(),getConversationContext(chatId)]);let parsed;try{parsed=await getIntentProvider().parse(message,{businessDate,activeProjectNames:projects.map(x=>x.name),activeEmployeeNames:employees.map(x=>x.name),previousFilters:previous});}catch{return{text:"לא הצלחתי להבין את ההודעה כרגע. אפשר לנסות שוב או להשתמש ב-/help."};}
  if(parsed.intent==="UNKNOWN")return{text:"לא הצלחתי להבין את הבקשה. ניתן לנסח מחדש או לשלוח /help."};
  if(parsed.intent==="CREATE_TIME_ENTRIES"){if(parsed.missing_information.includes("hours")||parsed.create_groups.some(g=>g.entries.some(e=>e.regular_hours===null)))return{text:"כמה שעות עבד כל עובד? לא נשמור דיווח בלי מספר שעות מפורש."};const resolved:ResolvedDraftEntry[]=[];for(const group of parsed.create_groups){const date=resolveDateReference(group.date_reference,businessDate);if(!date)return{text:`התאריך "${group.date_reference}" אינו תקין. נא לכתוב תאריך כמו 30/09/2026.`};const project=resolveEntity(group.project_reference,projects);if(project.kind!=="resolved")return{text:entityError("project",group.project_reference,project)};for(const entry of group.entries){const employee=resolveEntity(entry.employee_reference,employees);if(employee.kind!=="resolved")return{text:entityError("employee",entry.employee_reference,employee)};const regular=Number(entry.regular_hours),overtime=Number(entry.overtime_hours??0);if(!Number.isFinite(regular)||regular<0||overtime<0||regular+overtime<=0||regular+overtime>24)return{text:`מספר השעות עבור ${employee.entity.name} אינו תקין.`};resolved.push({work_date:date,employee_id:employee.entity.id,employee_name:employee.entity.name,project_id:project.entity.id,project_name:project.entity.name,regular_hours:regular,overtime_hours:overtime,notes:entry.notes,existing_hours:null});}}
    const existing=await findExistingEntries(resolved);resolved.forEach(e=>e.existing_hours=existing.get(`${e.employee_id}:${e.project_id}:${e.work_date}`)??null);const hasDuplicates=resolved.some(e=>e.existing_hours!==null);const draft=await createTelegramDraft({chatId,telegramUserId:userId,entries:resolved,messageHash:createHash("sha256").update(message).digest("hex"),allowUpdates:hasDuplicates});const confirmAction=hasDuplicates?"update":"confirm";return{text:formatDraft(resolved,hasDuplicates),inlineKeyboard:[[{text:hasDuplicates?"✅ אישור ועדכון":"✅ אישור",callback_data:`${confirmAction}:${draft.id}`},{text:"❌ ביטול",callback_data:`cancel:${draft.id}`}]]};}
  const report=parsed.report;if(!report)return{text:"לא הצלחתי להבין את הדוח המבוקש."};const projectRef=report.project_reference||String(previous?.projectReference||"")||null,employeeRef=report.employee_reference||String(previous?.employeeReference||"")||null;let project:NamedEntity|undefined,employee:NamedEntity|undefined;if(projectRef){const r=resolveEntity(projectRef,projects);if(r.kind!=="resolved")return{text:entityError("project",projectRef,r)};project=r.entity;}if(employeeRef){const r=resolveEntity(employeeRef,employees);if(r.kind!=="resolved")return{text:entityError("employee",employeeRef,r)};employee=r.entity;}const range=reportRange(report,businessDate,previous);if(!range)return{text:"טווח התאריכים אינו תקין."};const rows=await queryReport({employeeId:employee?.id,projectId:project?.id,...range});await saveConversationContext(chatId,{employeeReference:employee?.name||null,projectReference:project?.name||null,employeeId:employee?.id||null,projectId:project?.id||null,...range});if(!rows.length)return{text:"לא נמצאו דיווחים התואמים לבקשה."};const total=rows.reduce((a,x)=>a+x.regular_hours+x.overtime_hours,0),days=new Set(rows.map(x=>x.work_date)).size;const title=[employee?.name,project?.name].filter(Boolean).join(" — ")||"סיכום שעות";const grouped=new Map<string,{days:Set<string>;hours:number}>();rows.forEach(x=>{const name=project&&!employee?`${x.employee?.first_name||""} ${x.employee?.last_name||""}`.trim():employee&&!project?(x.project?.name||"פרויקט לא ידוע"):"";if(name){const g=grouped.get(name)||{days:new Set<string>(),hours:0};g.days.add(x.work_date);g.hours+=x.regular_hours+x.overtime_hours;grouped.set(name,g);}});const details=grouped.size?`\n\n${[...grouped].map(([name,g])=>`${name}\n${g.days.size} ימי עבודה\n${g.hours} שעות`).join("\n\n")}`:"";return{text:`📊 ${title}\n${formatBusinessDate(range.from)}–${formatBusinessDate(range.to)}${details}\n\n${days} ימי עבודה\nסה״כ: ${total} שעות\nמתוכן ${rows.reduce((a,x)=>a+x.overtime_hours,0)} שעות נוספות`};}
