export type NamedEntity={id:string;name:string;aliases?:string[]};
export type Resolution={kind:"resolved";entity:NamedEntity;confidence:number}|{kind:"ambiguous";options:NamedEntity[]}|{kind:"not_found"};
const finalLetters:Record<string,string>={ך:"כ",ם:"מ",ן:"נ",ף:"פ",ץ:"צ"};
export function normalizeHebrew(value:string){return value.normalize("NFKD").replace(/[׳״'"`]/g,"").replace(/[־–—-]/g," ").replace(/\b(אצל|של|פרויקט|הפרויקט|בפרויקט)\b/g," ").replace(/[^\p{L}\p{N}]+/gu," ").replace(/[ךםןףץ]/g,letter=>finalLetters[letter]).trim().replace(/\s+/g," ");}
function referenceVariants(value:string){const normalized=normalizeHebrew(value),variants=new Set([normalized]),queue=[normalized];for(let depth=0;depth<2;depth+=1){const current=queue.shift();if(!current)break;const words=current.split(" "),first=words[0];if(first.length>3&&/^[בלהו]/.test(first)){const stripped=[first.slice(1),...words.slice(1)].join(" ");variants.add(stripped);queue.push(stripped);}}return[...variants].filter(Boolean);}
function aliases(entity:NamedEntity){const normalized=normalizeHebrew(entity.name),tokens=normalized.split(" ").filter(token=>token.length>1);return [...new Set([normalized,tokens.join(" "),...tokens,...(entity.aliases||[]).map(normalizeHebrew)])];}
function distance(a:string,b:string){const previous=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let diagonal=previous[0];previous[0]=i;for(let j=1;j<=b.length;j++){const old=previous[j];previous[j]=Math.min(previous[j]+1,previous[j-1]+1,diagonal+(a[i-1]===b[j-1]?0:1));diagonal=old;}}return previous[b.length];}
function similarity(a:string,b:string){if(a===b)return 1;if(!a||!b)return 0;const edits=distance(a,b),longest=Math.max(a.length,b.length);if(edits===1&&longest<=4&&Math.min(a.length,b.length)>=3)return .8;return 1-edits/longest;}
function score(reference:string,alias:string){if(reference===alias)return 1;const refTokens=reference.split(" "),aliasTokens=alias.split(" ");if(refTokens.length>1){const overlap=refTokens.filter(token=>aliasTokens.includes(token)).length/Math.max(refTokens.length,aliasTokens.length);if(overlap>=0.5)return .82+overlap*.12;}if(reference.length>=3&&alias.includes(reference))return .86;if(Math.abs(reference.length-alias.length)>2)return 0;return similarity(reference,alias);}
export function resolveEntity(reference:string,entities:NamedEntity[]):Resolution{const variants=referenceVariants(reference);if(!variants.length)return{kind:"not_found"};const ranked=entities.map(entity=>({entity,score:Math.max(...variants.flatMap(ref=>aliases(entity).map(alias=>score(ref,alias))))})).sort((a,b)=>b.score-a.score);const top=ranked[0];if(!top||top.score<.78)return{kind:"not_found"};const plausible=ranked.filter(item=>item.score>=.78&&top.score-item.score<.1);if(plausible.length>1)return{kind:"ambiguous",options:plausible.map(item=>item.entity)};return{kind:"resolved",entity:top.entity,confidence:top.score};}
