"use client";
import Link from "next/link";
import { useState } from "react";
import { MoreVertical, Trash2, X } from "lucide-react";
import { deleteTimeEntry } from "@/app/(app)/time-entries/actions";
import { formatHebrewDate } from "@/lib/date-ranges";

type Props={entry:{id:string;work_date:string;regular_hours:number;overtime_hours:number;employee_name:string;project_name:string};returnTo:string};
export function TimeEntryActions({entry,returnTo}:Props){const [open,setOpen]=useState(false),[confirm,setConfirm]=useState(false);const total=Number(entry.regular_hours)+Number(entry.overtime_hours);return <div className="relative inline-flex"><button type="button" aria-label="פעולות לדיווח" aria-expanded={open} onClick={()=>setOpen(value=>!value)} className="p-2 rounded hover:bg-slate-100"><MoreVertical size={18}/></button>{open&&<div className="absolute left-0 top-9 z-20 min-w-28 card p-1 shadow-lg"><Link href={`/time-entries/${entry.id}/edit?returnTo=${encodeURIComponent(returnTo)}`} className="block px-3 py-2 text-sm hover:bg-slate-50 rounded">עריכה</Link><button type="button" onClick={()=>{setOpen(false);setConfirm(true)}} className="block w-full text-right px-3 py-2 text-sm text-red-700 hover:bg-red-50 rounded">מחיקה</button></div>}{confirm&&<div role="dialog" aria-modal="true" aria-labelledby={`delete-${entry.id}`} className="fixed inset-0 z-50 bg-slate-950/45 grid place-items-center p-4"><div className="card w-full max-w-md p-5"><div className="flex justify-between items-start"><div><Trash2 className="text-red-600 mb-3"/><h2 id={`delete-${entry.id}`} className="text-xl font-bold">מחיקת דיווח שעות</h2></div><button type="button" aria-label="סגירה" onClick={()=>setConfirm(false)} className="p-2"><X size={20}/></button></div><p className="text-slate-600 mt-3">האם למחוק את הדיווח של {entry.employee_name} מתאריך {formatHebrewDate(entry.work_date)} בפרויקט {entry.project_name}?</p><div className="bg-slate-50 rounded p-4 my-4 text-sm space-y-1"><b className="block">{entry.employee_name}</b><span className="block">{entry.project_name}</span><span className="block">{formatHebrewDate(entry.work_date)}</span><span className="block font-bold">{total} שעות</span></div><form action={deleteTimeEntry} className="flex justify-end gap-2"><input type="hidden" name="id" value={entry.id}/><input type="hidden" name="return_to" value={returnTo}/><button type="button" className="btn btn-secondary" onClick={()=>setConfirm(false)}>ביטול</button><button className="btn bg-red-600 text-white hover:bg-red-700">מחיקת דיווח</button></form></div></div>}</div>}
