"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { editableTimeEntrySchema } from "@/lib/time-entry-rules";

function safeReturnTo(value:FormDataEntryValue|null){const path=String(value||"/history");return /^\/(history|employees\/[^/]+|projects\/[^/]+\/work-days\/\d{4}-\d{2}-\d{2})(\?.*)?$/.test(path)?path:"/history";}
function withMessage(path:string,key:"success"|"error",message:string){const separator=path.includes("?")?"&":"?";return `${path}${separator}${key}=${encodeURIComponent(message)}`;}
async function refreshEntryViews(employeeId:string,projectId:string,date:string){revalidatePath("/dashboard");revalidatePath("/reports");revalidatePath("/history");revalidatePath(`/employees/${employeeId}`);revalidatePath(`/projects/${projectId}/work-days/${date}`);}

export async function updateTimeEntry(formData:FormData){const id=String(formData.get("id")||""),returnTo=safeReturnTo(formData.get("return_to"));const parsed=editableTimeEntrySchema.safeParse({work_date:formData.get("work_date"),employee_id:formData.get("employee_id"),project_id:formData.get("project_id"),regular_hours:formData.get("regular_hours"),overtime_hours:formData.get("overtime_hours"),notes:String(formData.get("notes")||"").trim()||null});if(!parsed.success)redirect(`/time-entries/${id}/edit?returnTo=${encodeURIComponent(returnTo)}&error=${encodeURIComponent(parsed.error.issues[0]?.message||"הנתונים אינם תקינים")}`);const s=await createClient();const [{data:employee},{data:project},{data:existing},{data:original}]=await Promise.all([s.from("employees").select("id").eq("id",parsed.data.employee_id).maybeSingle(),s.from("projects").select("id").eq("id",parsed.data.project_id).maybeSingle(),s.from("time_entries").select("id").eq("employee_id",parsed.data.employee_id).eq("project_id",parsed.data.project_id).eq("work_date",parsed.data.work_date).neq("id",id).maybeSingle(),s.from("time_entries").select("employee_id,project_id,work_date").eq("id",id).maybeSingle()]);if(!employee||!project||!original)redirect(`/time-entries/${id}/edit?returnTo=${encodeURIComponent(returnTo)}&error=${encodeURIComponent("העובד, הפרויקט או הדיווח אינם קיימים")}`);if(existing)redirect(`/time-entries/${id}/edit?returnTo=${encodeURIComponent(returnTo)}&error=${encodeURIComponent("כבר קיים דיווח לעובד, לפרויקט ולתאריך שנבחרו. לא בוצע שינוי.")}`);const {error}=await s.from("time_entries").update(parsed.data).eq("id",id);if(error)redirect(`/time-entries/${id}/edit?returnTo=${encodeURIComponent(returnTo)}&error=${encodeURIComponent(error.message)}`);await refreshEntryViews(original.employee_id,original.project_id,original.work_date);await refreshEntryViews(parsed.data.employee_id,parsed.data.project_id,parsed.data.work_date);redirect(withMessage(returnTo,"success","הדיווח עודכן בהצלחה"));}

export async function deleteTimeEntry(formData:FormData){const id=String(formData.get("id")||""),returnTo=safeReturnTo(formData.get("return_to"));const s=await createClient();const {data:entry}=await s.from("time_entries").select("employee_id,project_id,work_date").eq("id",id).maybeSingle();if(!entry)redirect(withMessage(returnTo,"error","הדיווח אינו קיים או שכבר נמחק"));const {error}=await s.from("time_entries").delete().eq("id",id);if(error)redirect(withMessage(returnTo,"error","לא ניתן למחוק את הדיווח"));await refreshEntryViews(entry.employee_id,entry.project_id,entry.work_date);redirect(withMessage(returnTo,"success","הדיווח נמחק בהצלחה"));}
